USE [master]
GO
/****** Object:  Database [PersonalDetailDB]    Script Date: 29-11-2020 9.12.00 PM ******/
CREATE DATABASE [PersonalDetailDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PersonalDetailDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\PersonalDetailDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PersonalDetailDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\PersonalDetailDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [PersonalDetailDB] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PersonalDetailDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [PersonalDetailDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [PersonalDetailDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [PersonalDetailDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [PersonalDetailDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [PersonalDetailDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [PersonalDetailDB] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [PersonalDetailDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [PersonalDetailDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [PersonalDetailDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [PersonalDetailDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [PersonalDetailDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [PersonalDetailDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [PersonalDetailDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [PersonalDetailDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [PersonalDetailDB] SET  ENABLE_BROKER 
GO
ALTER DATABASE [PersonalDetailDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [PersonalDetailDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [PersonalDetailDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [PersonalDetailDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [PersonalDetailDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [PersonalDetailDB] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [PersonalDetailDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [PersonalDetailDB] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [PersonalDetailDB] SET  MULTI_USER 
GO
ALTER DATABASE [PersonalDetailDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [PersonalDetailDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [PersonalDetailDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [PersonalDetailDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [PersonalDetailDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [PersonalDetailDB] SET QUERY_STORE = OFF
GO
USE [PersonalDetailDB]
GO
/****** Object:  Table [dbo].[__EFMigrationsHistory]    Script Date: 29-11-2020 9.12.01 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__EFMigrationsHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PersonalDetails]    Script Date: 29-11-2020 9.12.02 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PersonalDetails](
	[PId] [int] IDENTITY(1,1) NOT NULL,
	[PersonName] [nvarchar](100) NOT NULL,
	[PhoneNumber] [varchar](10) NOT NULL,
	[Age] [varchar](3) NOT NULL,
 CONSTRAINT [PK_PersonalDetails] PRIMARY KEY CLUSTERED 
(
	[PId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [PersonalDetailDB] SET  READ_WRITE 
GO
